# fly.toml app configuration file generated for zoltan-antal-wedding-website-backend on 2024-07-04T15:16:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zoltan-antal-wedding-website-backend'
primary_region = 'lhr'

[deploy]

[processes]

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
